### ISSUE TITLE
Use more than 6 faces?

### ISSUE THREAD

**Issue by holysanctity** [almaan/diceconverter#1]
Hello, thank you for making this converter. I was wondering, is it possible to modify the code to use more than 6 faces for 2, 3, and 6? Thank you!

**Comment by almaan** [comment]
Hey @holysanctity ,

glad you liked this - now fairly old - toy project. I'm sure I can help you, but must confess that I'm not fully sure what exactly it is that you are requesting, perhaps you could elaborate some on what you mean by  _"more than 6 faces for 2,3 and 6"_? Do you mean to have these faces rotated and flipped, i.e., not always in the same configuration?

Best.
A

**Comment by holysanctity** [comment]
Dear almaan, yes! That is what I mean. Just taking into consideration that 2, 3, and 6 can have rotated versions. And sometimes, 2 will be manufactured differently depending on the company. Here is a list of images of what I mean visually:

https://imgur.com/a/KZOeqwz Thank you so much for the reply !

![1 - VZ0ThJw](https://user-images.githubusercontent.com/86687413/124167654-7a17e000-da61-11eb-8474-a17e0ac801c6.jpg)
![2 - LcOg6e3](https://user-images.githubusercontent.com/86687413/124167658-7ab07680-da61-11eb-8b98-b9892ceaa2ce.jpg)
![3 - MkbntuV](https://user-images.githubusercontent.com/86687413/124167661-7ab07680-da61-11eb-8c03-a17a1b976d04.jpg)
![4 - EeH3yUL](https://user-images.githubusercontent.com/86687413/124167663-7b490d00-da61-11eb-881c-7c6a333192bb.jpg)
![5 - QuayeTe](https://user-images.githubusercontent.com/86687413/124167664-7b490d00-da61-11eb-8450-fd9efabe7864.jpg)
![6 - Q3VsRTt](https://user-images.githubusercontent.com/86687413/124167666-7b490d00-da61-11eb-9fd4-e92221cab444.jpg)
![7 - lkYjrDs](https://user-images.githubusercontent.com/86687413/124167669-7be1a380-da61-11eb-8a28-cf7bc4a4a3d8.jpg)
![8 - Ud5A1Iw](https://user-images.githubusercontent.com/86687413/124167673-7be1a380-da61-11eb-8763-105b4696711c.jpg)
![9 - odixN6Y](https://user-images.githubusercontent.com/86687413/124167676-7c7a3a00-da61-11eb-8eff-fa1b0055bacf.jpg)
![10 - sxBuqnd](https://user-images.githubusercontent.com/86687413/124167678-7c7a3a00-da61-11eb-8eb4-e842cef009aa.jpg)
![11 - syeVQ7O](https://user-images.githubusercontent.com/86687413/124167680-7c7a3a00-da61-11eb-9437-ef21476ce017.jpg)
![12 - mHE0blA](https://user-images.githubusercontent.com/86687413/124167682-7d12d080-da61-11eb-8552-7277e82c1d1a.jpg)
![13 - PwxHwrb](https://user-images.githubusercontent.com/86687413/124167687-7d12d080-da61-11eb-9937-a4a985465744.jpg)

**Comment by almaan** [comment]
@holysanctity I see I see, yes, that should be fully possible, give me a day and I'll tend to it!

**Comment by almaan** [comment]
@holysanctity the requested feature has now been added, if you pull the latest version and follow the instructions in the README I believe you should be able to achieve what you are were asking for. If not, let me know - and if indeed you are happy with the adjustments, I would kindly ask you to close this issue!

Thanks for a good suggestions and posting it here!
/A

**Comment by holysanctity** [comment]
Works amazingly, thank you @almaan !
